// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'terminal.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -492108261;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_flutter_alacritty',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  int crateApiSimpleAddTerminal({required int rows, required int cols});

  int crateApiSimpleAddTerminalWithPrefs({
    required int rows,
    required int cols,
    required TermPreferences prefs,
  });

  Stream<int> crateApiSimpleCreateTerminalStream();

  TerminalFrame? crateApiSimpleGetTerminalFrame({required int id});

  TermPreferences? crateApiSimpleGetTerminalPrefs({required int id});

  Future<void> crateApiSimpleInitApp();

  TermPreferences crateApiSimpleLoadConfigPrefs();

  void crateApiSimpleRemoveTerminal({required int id});

  void crateApiSimpleSaveConfigPrefs({required TermPreferences prefs});

  void crateApiSimpleScrollTerminal({required int id, required int lines});

  void crateApiSimpleSendInput({required int id, required String input});

  void crateApiSimpleSetActiveTerminal({required int id});

  Future<TermPreferences> crateApiSimpleTermPreferencesDefault();

  void crateApiSimpleUpdateTerminalPrefs({
    required int id,
    required TermPreferences prefs,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  int crateApiSimpleAddTerminal({required int rows, required int cols}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(rows, serializer);
          sse_encode_u_16(cols, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleAddTerminalConstMeta,
        argValues: [rows, cols],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAddTerminalConstMeta => const TaskConstMeta(
    debugName: "add_terminal",
    argNames: ["rows", "cols"],
  );

  @override
  int crateApiSimpleAddTerminalWithPrefs({
    required int rows,
    required int cols,
    required TermPreferences prefs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(rows, serializer);
          sse_encode_u_16(cols, serializer);
          sse_encode_box_autoadd_term_preferences(prefs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleAddTerminalWithPrefsConstMeta,
        argValues: [rows, cols, prefs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAddTerminalWithPrefsConstMeta =>
      const TaskConstMeta(
        debugName: "add_terminal_with_prefs",
        argNames: ["rows", "cols", "prefs"],
      );

  @override
  Stream<int> crateApiSimpleCreateTerminalStream() {
    final sink = RustStreamSink<int>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_u_32_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 3,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiSimpleCreateTerminalStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleCreateTerminalStreamConstMeta =>
      const TaskConstMeta(
        debugName: "create_terminal_stream",
        argNames: ["sink"],
      );

  @override
  TerminalFrame? crateApiSimpleGetTerminalFrame({required int id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_terminal_frame,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetTerminalFrameConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetTerminalFrameConstMeta =>
      const TaskConstMeta(debugName: "get_terminal_frame", argNames: ["id"]);

  @override
  TermPreferences? crateApiSimpleGetTerminalPrefs({required int id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_term_preferences,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetTerminalPrefsConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetTerminalPrefsConstMeta =>
      const TaskConstMeta(debugName: "get_terminal_prefs", argNames: ["id"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  TermPreferences crateApiSimpleLoadConfigPrefs() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_term_preferences,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleLoadConfigPrefsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleLoadConfigPrefsConstMeta =>
      const TaskConstMeta(debugName: "load_config_prefs", argNames: []);

  @override
  void crateApiSimpleRemoveTerminal({required int id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleRemoveTerminalConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRemoveTerminalConstMeta =>
      const TaskConstMeta(debugName: "remove_terminal", argNames: ["id"]);

  @override
  void crateApiSimpleSaveConfigPrefs({required TermPreferences prefs}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_term_preferences(prefs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleSaveConfigPrefsConstMeta,
        argValues: [prefs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSaveConfigPrefsConstMeta =>
      const TaskConstMeta(debugName: "save_config_prefs", argNames: ["prefs"]);

  @override
  void crateApiSimpleScrollTerminal({required int id, required int lines}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          sse_encode_i_32(lines, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleScrollTerminalConstMeta,
        argValues: [id, lines],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleScrollTerminalConstMeta =>
      const TaskConstMeta(
        debugName: "scroll_terminal",
        argNames: ["id", "lines"],
      );

  @override
  void crateApiSimpleSendInput({required int id, required String input}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          sse_encode_String(input, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleSendInputConstMeta,
        argValues: [id, input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSendInputConstMeta =>
      const TaskConstMeta(debugName: "send_input", argNames: ["id", "input"]);

  @override
  void crateApiSimpleSetActiveTerminal({required int id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleSetActiveTerminalConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSetActiveTerminalConstMeta =>
      const TaskConstMeta(debugName: "set_active_terminal", argNames: ["id"]);

  @override
  Future<TermPreferences> crateApiSimpleTermPreferencesDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_term_preferences,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleTermPreferencesDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTermPreferencesDefaultConstMeta =>
      const TaskConstMeta(debugName: "term_preferences_default", argNames: []);

  @override
  void crateApiSimpleUpdateTerminalPrefs({
    required int id,
    required TermPreferences prefs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          sse_encode_box_autoadd_term_preferences(prefs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleUpdateTerminalPrefsConstMeta,
        argValues: [id, prefs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleUpdateTerminalPrefsConstMeta =>
      const TaskConstMeta(
        debugName: "update_terminal_prefs",
        argNames: ["id", "prefs"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<int> dco_decode_StreamSink_u_32_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  TermPreferences dco_decode_box_autoadd_term_preferences(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_term_preferences(raw);
  }

  @protected
  TerminalFrame dco_decode_box_autoadd_terminal_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_terminal_frame(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  TermPreferences? dco_decode_opt_box_autoadd_term_preferences(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_term_preferences(raw);
  }

  @protected
  TerminalFrame? dco_decode_opt_box_autoadd_terminal_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_terminal_frame(raw);
  }

  @protected
  TermPreferences dco_decode_term_preferences(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return TermPreferences(
      fontFamily: dco_decode_String(arr[0]),
      fontSize: dco_decode_f_64(arr[1]),
      lineHeight: dco_decode_f_64(arr[2]),
      colorForeground: dco_decode_u_32(arr[3]),
      colorBackground: dco_decode_u_32(arr[4]),
      colorCursor: dco_decode_u_32(arr[5]),
      colorSelection: dco_decode_u_32(arr[6]),
      palette: dco_decode_list_prim_u_32_strict(arr[7]),
    );
  }

  @protected
  TerminalFrame dco_decode_terminal_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return TerminalFrame(
      rows: dco_decode_u_16(arr[0]),
      cols: dco_decode_u_16(arr[1]),
      content: dco_decode_String(arr[2]),
      attributes: dco_decode_list_prim_u_32_strict(arr[3]),
      cursorX: dco_decode_u_16(arr[4]),
      cursorY: dco_decode_u_16(arr[5]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<int> sse_decode_StreamSink_u_32_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  TermPreferences sse_decode_box_autoadd_term_preferences(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_term_preferences(deserializer));
  }

  @protected
  TerminalFrame sse_decode_box_autoadd_terminal_frame(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_terminal_frame(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  TermPreferences? sse_decode_opt_box_autoadd_term_preferences(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_term_preferences(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TerminalFrame? sse_decode_opt_box_autoadd_terminal_frame(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_terminal_frame(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TermPreferences sse_decode_term_preferences(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fontFamily = sse_decode_String(deserializer);
    var var_fontSize = sse_decode_f_64(deserializer);
    var var_lineHeight = sse_decode_f_64(deserializer);
    var var_colorForeground = sse_decode_u_32(deserializer);
    var var_colorBackground = sse_decode_u_32(deserializer);
    var var_colorCursor = sse_decode_u_32(deserializer);
    var var_colorSelection = sse_decode_u_32(deserializer);
    var var_palette = sse_decode_list_prim_u_32_strict(deserializer);
    return TermPreferences(
      fontFamily: var_fontFamily,
      fontSize: var_fontSize,
      lineHeight: var_lineHeight,
      colorForeground: var_colorForeground,
      colorBackground: var_colorBackground,
      colorCursor: var_colorCursor,
      colorSelection: var_colorSelection,
      palette: var_palette,
    );
  }

  @protected
  TerminalFrame sse_decode_terminal_frame(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_rows = sse_decode_u_16(deserializer);
    var var_cols = sse_decode_u_16(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_attributes = sse_decode_list_prim_u_32_strict(deserializer);
    var var_cursorX = sse_decode_u_16(deserializer);
    var var_cursorY = sse_decode_u_16(deserializer);
    return TerminalFrame(
      rows: var_rows,
      cols: var_cols,
      content: var_content,
      attributes: var_attributes,
      cursorX: var_cursorX,
      cursorY: var_cursorY,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_u_32_Sse(
    RustStreamSink<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_term_preferences(
    TermPreferences self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_term_preferences(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_terminal_frame(
    TerminalFrame self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_terminal_frame(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_term_preferences(
    TermPreferences? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_term_preferences(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_terminal_frame(
    TerminalFrame? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_terminal_frame(self, serializer);
    }
  }

  @protected
  void sse_encode_term_preferences(
    TermPreferences self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.fontFamily, serializer);
    sse_encode_f_64(self.fontSize, serializer);
    sse_encode_f_64(self.lineHeight, serializer);
    sse_encode_u_32(self.colorForeground, serializer);
    sse_encode_u_32(self.colorBackground, serializer);
    sse_encode_u_32(self.colorCursor, serializer);
    sse_encode_u_32(self.colorSelection, serializer);
    sse_encode_list_prim_u_32_strict(self.palette, serializer);
  }

  @protected
  void sse_encode_terminal_frame(TerminalFrame self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.rows, serializer);
    sse_encode_u_16(self.cols, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_list_prim_u_32_strict(self.attributes, serializer);
    sse_encode_u_16(self.cursorX, serializer);
    sse_encode_u_16(self.cursorY, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
