// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class TerminalCell {
  final String content;
  final int fg;
  final int bg;
  final bool bold;

  const TerminalCell({
    required this.content,
    required this.fg,
    required this.bg,
    required this.bold,
  });

  @override
  int get hashCode =>
      content.hashCode ^ fg.hashCode ^ bg.hashCode ^ bold.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerminalCell &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          fg == other.fg &&
          bg == other.bg &&
          bold == other.bold;
}

class TerminalFrame {
  final int rows;
  final int cols;
  final List<TerminalCell> cells;
  final int cursorX;
  final int cursorY;

  const TerminalFrame({
    required this.rows,
    required this.cols,
    required this.cells,
    required this.cursorX,
    required this.cursorY,
  });

  @override
  int get hashCode =>
      rows.hashCode ^
      cols.hashCode ^
      cells.hashCode ^
      cursorX.hashCode ^
      cursorY.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerminalFrame &&
          runtimeType == other.runtimeType &&
          rows == other.rows &&
          cols == other.cols &&
          cells == other.cells &&
          cursorX == other.cursorX &&
          cursorY == other.cursorY;
}
