// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class TerminalFrame {
  final int rows;
  final int cols;
  final String content;
  final Uint32List attributes;
  final int cursorX;
  final int cursorY;

  const TerminalFrame({
    required this.rows,
    required this.cols,
    required this.content,
    required this.attributes,
    required this.cursorX,
    required this.cursorY,
  });

  @override
  int get hashCode =>
      rows.hashCode ^
      cols.hashCode ^
      content.hashCode ^
      attributes.hashCode ^
      cursorX.hashCode ^
      cursorY.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerminalFrame &&
          runtimeType == other.runtimeType &&
          rows == other.rows &&
          cols == other.cols &&
          content == other.content &&
          attributes == other.attributes &&
          cursorX == other.cursorX &&
          cursorY == other.cursorY;
}
