// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class TerminalFrame {
  final int terminalId;
  final int rows;
  final int cols;
  final String cells;
  final Uint32List fg;
  final Uint32List bg;
  final Uint8List bold;
  final int cursorX;
  final int cursorY;

  const TerminalFrame({
    required this.terminalId,
    required this.rows,
    required this.cols,
    required this.cells,
    required this.fg,
    required this.bg,
    required this.bold,
    required this.cursorX,
    required this.cursorY,
  });

  @override
  int get hashCode =>
      terminalId.hashCode ^
      rows.hashCode ^
      cols.hashCode ^
      cells.hashCode ^
      fg.hashCode ^
      bg.hashCode ^
      bold.hashCode ^
      cursorX.hashCode ^
      cursorY.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerminalFrame &&
          runtimeType == other.runtimeType &&
          terminalId == other.terminalId &&
          rows == other.rows &&
          cols == other.cols &&
          cells == other.cells &&
          fg == other.fg &&
          bg == other.bg &&
          bold == other.bold &&
          cursorX == other.cursorX &&
          cursorY == other.cursorY;
}
