// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../terminal.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `active_id`, `terminals`

int addTerminal({required int rows, required int cols}) =>
    RustLib.instance.api.crateApiSimpleAddTerminal(rows: rows, cols: cols);

void removeTerminal({required int id}) =>
    RustLib.instance.api.crateApiSimpleRemoveTerminal(id: id);

void setActiveTerminal({required int id}) =>
    RustLib.instance.api.crateApiSimpleSetActiveTerminal(id: id);

TerminalFrame? getTerminalFrame({required int id}) =>
    RustLib.instance.api.crateApiSimpleGetTerminalFrame(id: id);

void sendInput({required int id, required String input}) =>
    RustLib.instance.api.crateApiSimpleSendInput(id: id, input: input);
